// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backend.Domain;

public partial class Adjuntos
{
    public int Idadjuntos { get; set; }

    public string NombreArchivo { get; set; }

    public string Extension { get; set; }

    public string MimeType { get; set; }

    public long? TamanioBytes { get; set; }

    public string Ruta { get; set; }

    public virtual ICollection<Productos> Productos { get; set; } = new List<Productos>();
}