// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backend.Domain;

public partial class Categorias
{
    public int IdCategoria { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public bool? Activo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime? FechaActualizacion { get; set; }

    public virtual ICollection<Productos> Productos { get; set; } = new List<Productos>();
}