// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backend.Domain;

public partial class Historialstock
{
    public int IdHistorial { get; set; }

    public int IdProducto { get; set; }

    public int StockAnterior { get; set; }

    public int StockNuevo { get; set; }

    public int? Diferencia { get; set; }

    public int? IdTransaccion { get; set; }

    public string Motivo { get; set; }

    public DateTime Fecha { get; set; }

    public virtual Productos IdProductoNavigation { get; set; }

    public virtual Transacciones IdTransaccionNavigation { get; set; }
}