// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backend.Domain;

public partial class Productos
{
    public int IdProducto { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public int IdCategoria { get; set; }

    public int Idadjuntos { get; set; }

    public decimal Precio { get; set; }

    public int Stock { get; set; }

    public bool? Activo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime? FechaActualizacion { get; set; }

    public virtual ICollection<Historialstock> Historialstock { get; set; } = new List<Historialstock>();

    public virtual Categorias IdCategoriaNavigation { get; set; }

    public virtual Adjuntos IdadjuntosNavigation { get; set; }

    public virtual ICollection<Transacciones> Transacciones { get; set; } = new List<Transacciones>();
}