// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backend.Domain;

public partial class Tipostransaccion
{
    public int IdTipoTransaccion { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public bool? Activo { get; set; }

    public virtual ICollection<Transacciones> Transacciones { get; set; } = new List<Transacciones>();
}