// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backend.Domain;

public partial class Transacciones
{
    public int IdTransaccion { get; set; }

    public DateTime Fecha { get; set; }

    public int IdTipoTransaccion { get; set; }

    public int IdProducto { get; set; }

    public int Cantidad { get; set; }

    public decimal PrecioUnitario { get; set; }

    public decimal? PrecioTotal { get; set; }

    public string Detalle { get; set; }

    public string NumeroDocumento { get; set; }

    public bool? Activo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public virtual ICollection<Historialstock> Historialstock { get; set; } = new List<Historialstock>();

    public virtual Productos IdProductoNavigation { get; set; }

    public virtual Tipostransaccion IdTipoTransaccionNavigation { get; set; }
}